// frontend/src/App.svelte
<script lang="ts">
  import "ninja-keys";
  import CodeMirror from "svelte-codemirror-editor";
  import { Prec } from "@codemirror/state";
  import { keymap } from "@codemirror/view";
  import { ListManifests, RunManifest } from "../wailsjs/go/main/App";
  import CommandPalette from "./CommandPalette.svelte";
  import { write } from "./output";
  import type { Output } from "./types";
  import { oneDark } from "@codemirror/theme-one-dark";

  let value = "";
  const hotkeysP = ListManifests().then((manifests) => {
    return manifests.map((manifest, idx) => {
      return {
        id: manifest.name,
        title: `${manifest.name} - ${manifest.description}`,
        hotkey: idx < 9 ? `cmd+${idx + 1}` : undefined,
        mdIcon: "apps",
        handler: async () => {
          console.log(`Running ${manifest.name} for input\n${value}`);
          try {
            const output = await RunManifest(manifest.id, value);
            if (write(output, manifest.output as Output) === false) {
              return;
            }
            value = output;
          } catch (e) {
            console.error("Error running manifest", e);
          }
        },
      };
    });
  });

  let extensions = [
    Prec.highest(
      keymap.of([
        {
          key: "Mod-k",
          run: () => {
            const ninja = document.querySelector("ninja-keys");
            ninja.open();
            return true;
          },
        },
      ])
    ),
  ];
</script>

<main>
  {#await hotkeysP}
    <p>Loading...</p>
  {:then hotkeys}
    <CommandPalette {hotkeys}>
      <CodeMirror
        basic={true}
        lineWrapping={true}
        bind:value
        styles={{
          "&": {
            width: "100vw",
            height: "100vh",
          },
        }}
        {extensions}
        theme={oneDark}
      />
    </CommandPalette>
  {:catch error}
    <p>{error.message}</p>
  {/await}
</main>

<style>
</style>

// frontend/src/App.tsx
// import { EditorView } from '@codemirror/view';
// import { EditorState } from '@codemirror/state';
// import { basicSetup, minimalSetup } from '@uiw/codemirror-extensions-basic-setup';

import { langs } from "@uiw/codemirror-extensions-langs";
import { gruvboxDark } from "@uiw/codemirror-theme-gruvbox-dark";
import CodeMirror, { ReactCodeMirrorRef } from "@uiw/react-codemirror";
import React from "react";

import styles from "./App.module.css";
import { ListManifests, RunManifest } from "../wailsjs/go/main/App";
import { CommandPalette } from "./CommandPalette";
import "./global.css";
import { manifest } from "wailsjs/go/models";
import { Output } from "./types";
import { write } from "./output";

const extensions = [
  langs.css(),
  langs.javascript({ jsx: true }),
  langs.typescript(),
  langs.html(),
  langs.json(),
  langs.markdown(),
];

const emptyManifests: manifest.Manifest[] = [];

function App() {
  const valueRef = React.useRef<string>("");
  const codeMirrorRef = React.useRef<ReactCodeMirrorRef>(null);
  const setValue = React.useCallback((value: string) => {
    valueRef.current = value;
  }, []);

  const [manifests, setManifests] = React.useState(emptyManifests);
  const runManifest = React.useCallback(async (manifest: manifest.Manifest) => {
    try {
      const output = await RunManifest(manifest.id, valueRef.current);
      if (write(output, manifest.output as Output) === false) {
        return;
      }
      if (!codeMirrorRef.current) {
        return;
      }
      if (!codeMirrorRef.current.view) {
        return;
      }
      const view = codeMirrorRef.current.view;
      view.dispatch({
        changes: { from: 0, to: view.state.doc.length, insert: output },
      });
    } catch (e) {
      console.error("Error running manifest", e);
    }
  }, []);

  React.useEffect(() => {
    async function loadManifests() {
      const manifests = await ListManifests();
      setManifests(manifests);
    }
    loadManifests();
  }, []);

  return (
    <React.Fragment>
      <CodeMirror
        ref={codeMirrorRef}
        className={styles.editor}
        value={valueRef.current}
        extensions={extensions}
        theme={gruvboxDark}
        onChange={setValue}
      />
      <div className={styles.statusBar}>
        <div className={styles.statusBarItem}>Ln 1, Col 1</div>
      </div>
      <CommandPalette manifests={manifests} runManifest={runManifest} />
    </React.Fragment>
  );
}

export default App;
